name: Build and Push Backend to ECR

on:
  push:
    branches: [main]

jobs:
  push-ecr:
    env:
      PORT: 3000
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Push image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_URI }}:latest
          
      - name: Delete old ECR images (keep latest 2)
        run: |
          REPO_NAME=$(basename ${{ secrets.ECR_REPOSITORY_URI }})

          aws ecr describe-images \
            --repository-name "$REPO_NAME" \
            --region ${{ secrets.AWS_REGION }} \
            --query 'sort_by(imageDetails,&imagePushedAt)[::-1]' \
            --output json > images.json

          TOTAL=$(jq 'length' images.json)
          echo "Total image versions: $TOTAL"

          if [ "$TOTAL" -gt 2 ]; then
            DIGESTS_TO_DELETE=$(jq -r '.[2:][].imageDigest' images.json)
            for DIGEST in $DIGESTS_TO_DELETE; do
              echo "Deleting old image digest: $DIGEST"
              aws ecr batch-delete-image \
                --repository-name "$REPO_NAME" \
                --region ${{ secrets.AWS_REGION }} \
                --image-ids imageDigest="$DIGEST"
            done
          else
            echo "2 or fewer versions exist, nothing to delete."
          fi